name: Natrix
favicon: null
layout_spectrum: 0.79241
typography_spectrum: 0.19542
title: Natrix
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#ffffff'
    - '#d7d7de'
    - '#4b5263'
    - '#808598'
  brandStrength: 0.4375
  lightness: 0.4375
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
