name: NatrixMusic
favicon: null
layout_spectrum: 0.4938289728015661
typography_spectrum: 0.7932646912522614
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.3533158004283905
  lightness: 0.10866049001924694
  saturation: 0.6031716060824692
  rhythmicContrast: 0.6583699430339038
purpose: []
