name: NatrixMusic
favicon: null
layout_spectrum: 0.93114
typography_spectrum: 0.7932646912522614
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d8d8d8'
    - '#0c0e1b'
    - '#48263e'
    - '#938f8d'
    - '#5d5557'
  brandStrength: 0.625
  lightness: 0.1875
  saturation: 0
  rhythmicContrast: 0.6583699430339038
purpose: []
